import { Subject } from '../types/subject';
import { Topic } from '../types/topic';
import { Schedule } from '../types/schedule';

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'subj-os',
    Subject_Name: 'Operating Systems',
    Subject_Importance: 'Urgent',
    Subject_Description: 'Core systems concepts, processes, memory management, scheduling algorithms, and storage.',
    Subject_Color: '#8b5cf6', // Violet
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-cn',
    Subject_Name: 'Computer Networks',
    Subject_Importance: 'Important',
    Subject_Description: 'Network layers, TCP/IP, flow and congestion control, routing protocols, and network security.',
    Subject_Color: '#06b6d4', // Cyan
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-coa',
    Subject_Name: 'Computer Organization & Architecture',
    Subject_Importance: 'High Scoring',
    Subject_Description: 'Instruction pipelining, cache memory hierarchy, addressing modes, ALU design, and microarchitecture.',
    Subject_Color: '#10b981', // Emerald
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-dbms',
    Subject_Name: 'Database Management Systems',
    Subject_Importance: 'Normal',
    Subject_Description: 'Relational algebra, SQL, Normalization, ACID transactions, indexing with B+ trees.',
    Subject_Color: '#3b82f6', // Blue
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-algo',
    Subject_Name: 'Algorithms & Data Structures',
    Subject_Importance: 'High Scoring',
    Subject_Description: 'Asymptotic complexity, divide and conquer, dynamic programming, graph algorithms, greedy heuristics.',
    Subject_Color: '#f59e0b', // Amber
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-toc',
    Subject_Name: 'Theory of Computation',
    Subject_Importance: 'Important',
    Subject_Description: 'Automata theory, regular expressions, context-free grammars, Turing machines, and undecidability.',
    Subject_Color: '#ec4899', // Pink
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'subj-cd',
    Subject_Name: 'Compiler Design',
    Subject_Importance: 'Low Scoring',
    Subject_Description: 'Lexical analysis, top-down and bottom-up parsing, intermediate code representation, and optimization.',
    Subject_Color: '#6366f1', // Indigo
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TOPICS: Topic[] = [
  // ================= OPERATING SYSTEMS =================
  // 1. CPU Scheduling (Parent)
  {
    id: 'top-os-cpu',
    Subject_Id: 'subj-os',
    Parent_Id: null,
    Topic_Name: 'CPU Scheduling',
    Topic_Description: 'Fundamental CPU allocation policies, preemptive vs non-preemptive scheduling, turnaround and waiting time metrics.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Needs Attention',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 2,
      Deadline: '2026-08-30',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 2.5,
    Topic_Sessions: [
      {
        id: 'sess-os-1',
        start_time: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        end_time: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 60 * 1.5).toISOString(),
        duration_seconds: 5400,
        notes: 'Reviewed Gantt charts, Average Waiting Time calculations and Preemptive priority comparison.',
      },
      {
        id: 'sess-os-2',
        start_time: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
        end_time: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1 + 1000 * 60 * 60 * 1).toISOString(),
        duration_seconds: 3600,
        notes: 'Solved 15 DPP questions on Round Robin with varying time quantums.',
      },
    ],
    Topic_Blocks: [
      {
        id: 'block-os-1',
        type: 'note',
        order: 1,
        data: {
          title: 'Key Scheduling Goals & Formulas',
          text: 'Turnaround Time (TAT) = Completion Time - Arrival Time\nWaiting Time (WT) = TAT - Burst Time\nResponse Time = Time of first response - Arrival Time',
          noteColor: 'purple',
        },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'block-os-2',
        type: 'link',
        order: 2,
        data: {
          title: 'Operating Systems: Three Easy Pieces — Scheduling Chapter',
          url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched.pdf',
        },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'block-os-3',
        type: 'text',
        order: 3,
        data: {
          text: 'Refer to https://en.wikipedia.org/wiki/Scheduling_(computing) for standard benchmarking comparison between multi-level feedback queues and proportional share scheduling.',
        },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Children of CPU Scheduling
  {
    id: 'top-os-fcfs',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-cpu',
    Topic_Name: 'FCFS (First-Come, First-Served)',
    Topic_Description: 'Non-preemptive scheduling with Convoy Effect vulnerability.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0.8,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-sjf',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-cpu',
    Topic_Name: 'SJF (Shortest Job First)',
    Topic_Description: 'Optimal average waiting time for non-preemptive, requires CPU burst estimation.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0.7,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-srtf',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-cpu',
    Topic_Name: 'SRTF (Shortest Remaining Time First)',
    Topic_Description: 'Preemptive variant of SJF. Prone to starvation of longer bursts.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: true,
      Lecture_Needed: 1,
      Deadline: '2026-08-28',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 1.2,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-rr',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-cpu',
    Topic_Name: 'Round Robin Scheduling',
    Topic_Description: 'Time slicing via fixed quantum q. Trade-off between responsiveness and context-switching overhead.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Important',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-08-29',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 1.5,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-priority',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-cpu',
    Topic_Name: 'Priority Scheduling & Aging',
    Topic_Description: 'Static vs dynamic priorities. Starvation resolution through aging techniques.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-09-02',
      Recall_Activity: false,
      Practice_DPP: false,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 5,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 2. Process Management (Parent)
  {
    id: 'top-os-proc',
    Subject_Id: 'subj-os',
    Parent_Id: null,
    Topic_Name: 'Process Management & Synchronization',
    Topic_Description: 'Process states, PCB structure, fork/exec, IPC, Critical Section problem, and Semaphores.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 3,
      Deadline: '2026-09-05',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 3.2,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Children of Process Management
  {
    id: 'top-os-proc-states',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-proc',
    Topic_Name: 'Process States & Transitions',
    Topic_Description: 'New, Ready, Running, Waiting, Terminated, and Suspended state diagrams.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0.9,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-pcb',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-proc',
    Topic_Name: 'Process Control Block (PCB)',
    Topic_Description: 'Process identification, register state, program counter, memory management info, accounting.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0.5,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-ctx',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-proc',
    Topic_Name: 'Context Switching Overhead',
    Topic_Description: 'State saving and restoring mechanism, TLB flushes, cache pollution penalties.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Important',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-08-31',
      Recall_Activity: true,
      Practice_DPP: false,
    },
    Topic_Study_Hours: 1.0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-semaphores',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-proc',
    Topic_Name: 'Semaphores & Classical Sync Problems',
    Topic_Description: 'Counting and binary semaphores, Producer-Consumer, Dining Philosophers, Readers-Writers.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: true,
      Lecture_Needed: 2,
      Deadline: '2026-09-04',
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 3. Deadlocks (Parent)
  {
    id: 'top-os-deadlock',
    Subject_Id: 'subj-os',
    Parent_Id: null,
    Topic_Name: 'Deadlocks',
    Topic_Description: 'Coffman conditions, resource allocation graphs, Banker’s Algorithm for avoidance, and detection.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 2,
      Deadline: '2026-09-06',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 1.8,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-os-bankers',
    Subject_Id: 'subj-os',
    Parent_Id: 'top-os-deadlock',
    Topic_Name: 'Banker’s Algorithm & Safe Sequences',
    Topic_Description: 'Matrix calculations (Allocation, Max, Available, Need) to determine safe state progression.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'High Priority',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-09-07',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 4. Memory Management (Parent)
  {
    id: 'top-os-mem',
    Subject_Id: 'subj-os',
    Parent_Id: null,
    Topic_Name: 'Memory Management & Virtual Memory',
    Topic_Description: 'Contiguous allocation, paging, segmentation, inverted page tables, page replacement algorithms (FIFO, LRU, Optimal).',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Important',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 4,
      Deadline: '2026-09-12',
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= COMPUTER NETWORKS =================
  {
    id: 'top-cn-osi',
    Subject_Id: 'subj-cn',
    Parent_Id: null,
    Topic_Name: 'OSI Model & TCP/IP Architecture',
    Topic_Description: 'Detailed responsibilities of physical, data link, network, transport, session, presentation, and application layers.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 3.0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-cn-flow',
    Subject_Id: 'subj-cn',
    Parent_Id: null,
    Topic_Name: 'Flow Control & Error Control (ARQ)',
    Topic_Description: 'Stop-and-Wait, Go-Back-N, and Selective Repeat protocols, window size equations, and channel utilization calculations.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Needs Attention',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-09-01',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 2.1,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-cn-routing',
    Subject_Id: 'subj-cn',
    Parent_Id: null,
    Topic_Name: 'IP Addressing, Subnetting & Routing',
    Topic_Description: 'Classless Inter-Domain Routing (CIDR), longest prefix match, Distance Vector (RIP), Link State (OSPF), BGP.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 3,
      Deadline: '2026-09-10',
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= COMPUTER ORGANIZATION & ARCHITECTURE =================
  {
    id: 'top-coa-cache',
    Subject_Id: 'subj-coa',
    Parent_Id: null,
    Topic_Name: 'Cache Memory Architecture & Mapping',
    Topic_Description: 'Direct, Associative, and Set-Associative mapping, cache miss classification (Compulsory, Capacity, Conflict), Write-Through vs Write-Back.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: true,
      Lecture_Needed: 2,
      Deadline: '2026-08-31',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 2.8,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-coa-pipe',
    Subject_Id: 'subj-coa',
    Parent_Id: null,
    Topic_Name: 'Instruction Pipelining & Hazards',
    Topic_Description: 'Pipeline speedup, throughput, structural hazards, data hazards (RAW, WAR, WAW), forwarding, and branch prediction.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Important',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'High',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 1,
      Deadline: '2026-09-03',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 2.4,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= DATABASE MANAGEMENT SYSTEMS =================
  {
    id: 'top-db-norm',
    Subject_Id: 'subj-dbms',
    Parent_Id: null,
    Topic_Name: 'Normalization & Functional Dependencies',
    Topic_Description: 'Closure of attribute sets, candidate keys, 1NF, 2NF, 3NF, and Boyce-Codd Normal Form (BCNF) decomposition losslessness.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 3.5,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-db-tx',
    Subject_Id: 'subj-dbms',
    Parent_Id: null,
    Topic_Name: 'Transactions & Concurrency Control',
    Topic_Description: 'ACID properties, serializability (conflict and view), precedence graphs, Two-Phase Locking (2PL), and strict 2PL.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Weak',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: true,
      Lecture_Needed: 2,
      Deadline: '2026-09-05',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 1.5,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= ALGORITHMS =================
  {
    id: 'top-algo-dp',
    Subject_Id: 'subj-algo',
    Parent_Id: null,
    Topic_Name: 'Dynamic Programming & Memoization',
    Topic_Description: 'Optimal substructure, overlapping subproblems, 0/1 Knapsack, Longest Common Subsequence, Matrix Chain Multiplication.',
    Topic_Status: 'Doing',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Medium',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 3,
      Deadline: '2026-09-08',
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 4.0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-algo-graph',
    Subject_Id: 'subj-algo',
    Parent_Id: null,
    Topic_Name: 'Graph Algorithms & Shortest Paths',
    Topic_Description: 'BFS, DFS, Dijkstra’s Single Source Shortest Path, Bellman-Ford, Floyd-Warshall, and Topological Sorting.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: true,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 3.5,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= THEORY OF COMPUTATION =================
  {
    id: 'top-toc-dfa',
    Subject_Id: 'subj-toc',
    Parent_Id: null,
    Topic_Name: 'Finite Automata & Regular Languages',
    Topic_Description: 'DFA minimization (Myhill-Nerode), NFA to DFA conversion, Pumping Lemma for regular languages.',
    Topic_Status: 'Done',
    Topic_Difficulty: 'Normal',
    Topic_Tags: {
      Done: true,
      Require_Practice: false,
      Confidence: 'High',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 0,
      Deadline: null,
      Recall_Activity: true,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 2.2,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'top-toc-turing',
    Subject_Id: 'subj-toc',
    Parent_Id: null,
    Topic_Name: 'Turing Machines & Undecidability',
    Topic_Description: 'Recursive and recursively enumerable languages, Halting Problem, Rice’s Theorem, and Post Correspondence Problem.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Revision Required',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: true,
      Redo: true,
      Lecture_Needed: 2,
      Deadline: '2026-09-14',
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ================= COMPILER DESIGN =================
  {
    id: 'top-cd-parsing',
    Subject_Id: 'subj-cd',
    Parent_Id: null,
    Topic_Name: 'Syntax Analysis & LR Parsers',
    Topic_Description: 'First & Follow set computations, LL(1) parse tables, LR(0), SLR(1), CLR(1), and LALR(1) item collections and conflict resolutions.',
    Topic_Status: 'To Do',
    Topic_Difficulty: 'Hard',
    Topic_Tags: {
      Done: false,
      Require_Practice: true,
      Confidence: 'Low',
      Skip: false,
      Star: false,
      Redo: false,
      Lecture_Needed: 2,
      Deadline: '2026-09-15',
      Recall_Activity: false,
      Practice_DPP: true,
    },
    Topic_Study_Hours: 0,
    Topic_Sessions: [],
    Topic_Blocks: [],
    Topic_Order: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sched-today',
    Schedule_Date: new Date().toISOString().split('T')[0],
    Schedule_Hours: 4,
    Schedule_Subjects: ['subj-os', 'subj-coa', 'subj-cn', 'subj-dbms'],
    Schedule_Tag_Filters: ['Require_Practice', 'Star', 'Deadline'],
    Subject_Allocations: {
      'subj-os': 60,
      'subj-coa': 60,
      'subj-cn': 60,
      'subj-dbms': 60,
    },
    Allocated_Topics: [
      {
        topic_id: 'top-os-cpu',
        subject_id: 'subj-os',
        topic_name: 'CPU Scheduling',
        subject_name: 'Operating Systems',
        allocated_minutes: 30,
        completed: false,
      },
      {
        topic_id: 'top-os-proc',
        subject_id: 'subj-os',
        topic_name: 'Process Management & Synchronization',
        subject_name: 'Operating Systems',
        allocated_minutes: 30,
        completed: false,
      },
      {
        topic_id: 'top-coa-cache',
        subject_id: 'subj-coa',
        topic_name: 'Cache Memory Architecture & Mapping',
        subject_name: 'Computer Organization & Architecture',
        allocated_minutes: 60,
        completed: false,
      },
      {
        topic_id: 'top-cn-flow',
        subject_id: 'subj-cn',
        topic_name: 'Flow Control & Error Control (ARQ)',
        subject_name: 'Computer Networks',
        allocated_minutes: 60,
        completed: false,
      },
      {
        topic_id: 'top-db-tx',
        subject_id: 'subj-dbms',
        topic_name: 'Transactions & Concurrency Control',
        subject_name: 'Database Management Systems',
        allocated_minutes: 60,
        completed: false,
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
